[package]
name = "shm-cached"
version = "0.1.0"
authors = ["Shish <shish@shishnet.org>"]
edition = "2018"
build = "build.rs"

[dependencies]
flexihash = "0.1"
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7"
tokio-rustls = "0.22"
warp = { version = "0.3", features = ["tls"] }
clap = { version = "3.1.18", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
utime = "0.3"
httpdate = "1"
futures = "0.3"
privdrop = "0.5"
gethostname = "0.2"
anyhow = "1"

[build-dependencies]
vergen = "3"