[package]
name = "shm-cached"
version = "0.1.0"
authors = ["Shish <shish@shishnet.org>"]
edition = "2018"
build = "build.rs"

[dependencies]
flexihash = "*"
tokio = { version = "0.2", features = ["full"] }
tokio-postgres = "*"
warp = { version = "0.2", features = ["tls"] }
pretty_env_logger = "*"
structopt = "*"
utime = "*"
httpdate = "*"
futures = "*"
log = "*"
privdrop = "*"
gethostname = "*"
tokio-rustls = "*"
hyper = "*"

[build-dependencies]
vergen = "3"