[package]
name = "shm-cached"
version = "0.1.0"
authors = ["Shish <shish@shishnet.org>"]
edition = "2018"
build = "build.rs"

[dependencies]
flexihash = "*"
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7"
tokio-rustls = "0.22"
warp = { version = "0.3", features = ["tls"] }
pretty_env_logger = "*"
structopt = "*"
utime = "*"
httpdate = "*"
futures = "*"
log = "*"
privdrop = "*"
gethostname = "*"

[build-dependencies]
vergen = "3"