name: Test & Publish

on:
  push:
  pull_request:

jobs:
  build:
    name: Build & Publish
    strategy:
      matrix:
        toolchain: ["1.67.0"]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set Up Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
          ~/.rustup/toolchains
          ~/.rustup/update-hashes
          ~/.rustup/settings.toml
        key: ${{ runner.os }}-rust-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.lock') }}
    - name: Set Up Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        command: build
        args: --release
    - name: Publish
      if: github.event_name == 'push'
      uses: eine/tip@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          target/release/shm-cached
        rm: true
