name: Test & Publish

on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set Up Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Set Up Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        toolchain: nightly
        command: build

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Up Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: build
          args: --release
      - name: Publish
        uses: eine/tip@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            target/release/shm-cached
          rm: true
