name: Test & Publish

on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    steps:
    - name: Publish
      uses: actions/upload-artifact@v2
      with:
        name: shm-cached
        path: target/release/shm-cached
